<div class="container" style="margin-top: 100px">
    <div class="main-content main-content--no-margin" style="">
        <h4><strong>1. GENERAL</strong></h4><p>These Terms and Conditions shall apply to the provision of all of Creative Kiwi’s services.</p><h4><strong><br>2. INTERPRETATION</strong></h4><p>In these Terms and Conditions and in any Contract to which these terms and conditions apply unless the context otherwise requires:</p><ol><li>Creative Kiwi means Creative Kiwi Limited;</li>
<li>Conditions mean these Terms and Conditions to be read and construed with each Estimate/Quotation provided by Creative Kiwi;</li>
<li>Client or Customer means the purchaser of products and/or services from Creative Kiwi.&nbsp;If the Client(s) comprises more than one person, each of those person’s liability and agreement is joint and several.</li>
<li>Where the Client is a trust, the trustee's liability shall not be limited to the assets of the trust;<br>Contract means an agreement between the Client and Creative Kiwi comprising of the</li>
<li>Estimate/Quotation and the Conditions and any variation agreed to in writing by Creative Kiwi;<br>Products and services mean&nbsp;the products sold by Creative Kiwi to the client;</li>
<li>Unless Creative Kiwi and the Client otherwise agree in writing:
<ol><li>In the event of any conflict arising between these Conditions and any agreement or contract these Terms and Conditions shall prevail; and</li>
<li>Estimates/Quotations by Creative Kiwi remain open for acceptance for 28 days from the date of the Estimate or Quotation.</li>
</ol></li>
</ol><h4><strong><br>3. CONTRACT FORMATION</strong></h4><p>No contract shall come into existence until the Client’s order has been accepted by Creative Kiwi. The Client may place an order by either:</p><ol><li>Accepting the Estimate or Quotation via Creative Kiwi’s website, by telephone, by email, in person or in writing; or</li>
<li>Paying the deposit (if any) referred to in the Estimate or Quotation; or<br>Communicating its order to Creative Kiwi in a manner otherwise than in accordance with (a) above. The</li>
<li>Client cannot cancel a contract after an order has been accepted by Creative Kiwi and is bound to pay the estimated or quoted price.</li>
</ol><h4><strong><br>4. PAYMENT</strong></h4><ol><li>Unless otherwise agreed in writing, prices are estimated and quoted in New Zealand Currency and shall be exclusive of GST.</li>
<li>Creative Kiwi will invoice the Client upon completion of the work unless the work is ongoing (past the end of any month) in which case Creative Kiwi will invoice the Client on a monthly time-taken basis. Unless otherwise agreed in writing, invoices are payable within fourteen (14) days of the date of that invoice.</li>
<li>Unless otherwise agreed in writing, payment of the products and services shall be made within fourteen (14) days following the date of invoice. Creative Kiwi reserves the right to require the Client to pay for Products and/or Services prior to their supply.</li>
<li>If the Client does not pay their account by the due date and has not entered into any payment arrangement (which is at Creative Kiwi’s sole discretion), Creative Kiwi reserves the right to stop working for the Client immediately and will not be liable to the Client for any loss that they may suffer as a result of such discontinuance.</li>
<li>Creative Kiwi reserves the right to correct any typographical or clerical errors contained in the prices or specifications.</li>
<li>Time for payment is of the essence and, without prejudice to any other rights of Creative Kiwi, if the Client fails to pay any sum payable pursuant to any Contract when due:
<ol><li>Creative Kiwi may treat the Contract as repudiated by the Customer or may until payment in full is made, suspend delivery of products without incurring any liability whatsoever to Creative Kiwi;</li>
<li>The Client shall (if so required by Creative Kiwi) pay interest to Creative Kiwi at the default interest rate of fourteen&nbsp;percent&nbsp;(14%) per annum. Interest shall be payable daily until the date when the payment is received; and</li>
<li>The Client shall be liable for all the expenses and costs (including indemnity legal costs) in relation to Creative Kiwi enforcing or attempting to enforce a Contract or these Terms and Conditions.</li>
</ol></li>
</ol><h4><strong><br>5. DEFAULT</strong></h4><p>In the event that:</p><ol><li>The amounts payable by the Client to Creative Kiwi are overdue, or the Client fails to meet any other obligation to Creative Kiwi, under this or any other Contract or agreement or in Creative Kiwi’s opinion the</li>
<li>Client is likely to be unable to meet any payment or other obligations to Creative Kiwi; or<br>The Client becomes insolvent, has a receiver appointed in respect of all or some of its assets, makes or is likely to make an arrangement with its creditors or has a liquidator (provisional or otherwise) appointed or is placed under statutory or official management; or</li>
<li>The Client no longer carries on business or threatens to cease carrying on business; or</li>
<li>The ownership or effective control of the Client is transferred or the nature of the Client’s business is materially altered; then</li>
</ol><p>Creative Kiwi shall be entitled to cancel all or any part of any Contract with the Client which remains unperformed, in addition to and without prejudice to its other remedies; and all amounts outstanding under this Contract or any other</p><h4><strong><br>6. INTELLECTUAL PROPERTY</strong></h4><ol><li>Unless otherwise agreed, Creative Kiwi shall retain copyright and intellectual property rights in all documents, reports, records, media, electronic files, drawings and designs prepared for and on the Client’s behalf.</li>
<li>The Client will be entitled to use the documents and any copies for the purposes for which they were intended however, unless otherwise agreed, the Client (or any other person or entity) is not permitted to make use of, or modify, any such document for any other purpose without Creative Kiwi’s agreement in writing. Concepts not chosen will remain the property of Creative Kiwi.</li>
<li>On completion and full payment of branding projects, the intellectual property rights of the Client’s logo design will transfer to the Client.</li>
<li>Where Creative Kiwi provides access to design files, access will be provided in PDF, JPG or PNG format.</li>
<li>Access to design files in other formats may incur additional costs for the Client.<br>Trademarking is the sole responsibility of the Client.</li>
</ol><h4><strong><br>7. LIMITATION OF LIABILITY</strong></h4><ol><li>The Client agrees that Creative Kiwi will not be liable for any indirect or consequential damages, including but not limited to, loss of profits or for any claim made on the Client by any other party, even though Creative Kiwi may have been notified of such damage or claims.<br>In particular, Creative Kiwi shall not be liable for any loss or damages arising, either directly or indirectly, from search engine rankings or social media marketing, including but not limited to any losses resulting from changes in search engine rankings, the closure of social media accounts and non-compliance with social media provider guidelines.</li>
<li>Creative Kiwi shall not be liable to the Client for any loss or damage directly or indirectly arising out of or in connection with any delay in delivery of the goods or failure to perform its obligations to the Client where such delay or failure is caused directly or indirectly by the Client (for example, by changing its requirements, not providing timely feedback or approval of proofs) or by an act of God, armed conflict, labour dispute, civil commotion, intervention of a government, inability to obtain labour, materials or manufacturing facilities, accidents, interruptions of, or delay in, transportation, weather conditions or any other cause beyond Creative Kiwi’s control.</li>
<li>The Client agrees to defend, indemnify and hold Creative Kiwi harmless from and against any and all claims, losses, liabilities and expenses (including legal costs) related to or arising out of the services provided by Creative Kiwi to the Client, including without limitation claims made by third parties (including the Client’s customers) related to any false advertising claims, liability claims for products or services sold by the Client, claims for patent, copyright or trademark infringement, claims due to disruption or malfunction of services provided by Creative Kiwi, or for any content submitted by the Client for publication by Creative Kiwi.&nbsp;</li>
<li>If,&nbsp;despite the above, Creative Kiwi is found to be liable to the Client, then its liability for any single event or series of related events is limited to the fees paid by the Client to Creative Kiwi for those particular services.</li>
<li>Due to the public nature of the Internet, all material submitted by the Client for publication will be considered publicly accessible. Creative Kiwi does not screen in advance any Client material submitted to Creative Kiwi for publication. Mint De sign’s publication of material submitted by the Client does not create any express or implied approval by Creative Kiwi of such material.</li>
</ol><h4><strong><br>8. WEBSITES</strong></h4><ol><li>Where Creative Kiwi has created or designed a website for the Client, the Client must make payment in full prior to the website ‘going live’ on the internet. Should payment not be made in full, Creative Kiwi reserves the right to shut down that website until such time as it receives payment in full. In the event that the website is already live, Creative Kiwi reserves the right to take the website down from the internet until such time as it receives payment in full.</li>
<li>The Client acknowledges and agrees that it will be liable for all of the costs restoring the website to the internet where it has been shut down due to non-payment.</li>
<li>If the Client has retained Creative Kiwi to host its website, Creative Kiwi will charge monthly fees, and if the Client falls into arrears in relation to those monthly payments, Creative Kiwi reserves the right to shut the website down and will not be liable for any consequences which might arise in the event of such a situation arising.</li>
<li>The Client agrees that it will be charged for any work it requests Creative Kiwi to complete or undertake that is outside of the scope of the estimate/ quote and the approved design. After going live, updates or changes the Client wishes to make to the website will also be chargeable.</li>
<li>Packaging and supplying website files for transfer or taking a website down will incur a cost and will be payable by the Client.</li>
</ol><h4><strong><br>9. STREET VIEW TRUSTED 360 TOURS</strong></h4><ol><li>Where the Client has engaged Creative Kiwi to create a Streetview Trusted 360 Tour, the Client must make payment in full prior to the 360 Tour ‘going live’ on the internet. Should payment not be made in full, Creative Kiwi reserves the right to shut down that 360 Tour and if it has already gone live on the internet, to take it down, until such time as it receives payment in full.</li>
<li>The Client acknowledges and agrees that it will be liable for all of the costs restoring the 360 Tour to the internet where it has been shut down due to non-payment.</li>
<li>The Client acknowledges and agrees that Creative Kiwi will not be liable to the Client for any losses in the event that Google makes any changes to Streetview Trusted, including but not limited to Google changing the way that Streetview Trusted operates or discontinuing the Streetview Trusted product.</li>
</ol><h4><strong><br>10. ONLINE MARKETING</strong></h4><ol><li>The Client acknowledges that Creative Kiwi incurs expenses and uses its expertise and intellectual property when it sets up online marketing campaigns for its clients. The Client also acknowledges that, unless otherwise agreed, any quote for marketing services does not include the transfer of any intellectual property rights from Creative Kiwi to the Client.</li>
<li>The Client acknowledges that Creative Kiwi retains the ownership of any advertising software accounts used to execute advertising campaigns on behalf of the Client.</li>
<li>In regards to programmatic marketing campaigns run through the Google Marketing Platform, which includes but is not limited to Google Display and Video 360, Google Campaign Manager and Google Search Ads 360, the Client acknowledges that Creative Kiwi has undertaken a contract directly with Google through an authorised reseller and that this contract, and ownership of the software account/s, is not transferable to the client.</li>
<li>In regards to Google Ads campaigns, in the event that the Client wishes to take over the online marketing account/s at the end of a marketing campaign, or where the Client terminates the campaign, the Client acknowledges that the Client will incur a fee for the transfer of the online marketing account/s and this fee will be payable in full in advance of the transfer.</li>
<li>From time to time, clients may choose to pause the online marketing campaign/s set up and managed by Creative Kiwi. The Client acknowledges and agrees that where the Client’s marketing campaign/s is/are paused, the Client will continue to be liable for Creative Kiwi’s monthly management fee.</li>
<li>In the event of a catastrophe, Creative Kiwi reserves the right to pause any online marketing campaign/s it manages,&nbsp;for a reasonable period of time, without prior notice to the Client.&nbsp;The Client acknowledges and agrees that where the Client’s marketing campaign/s is/are paused, the Client will continue to be liable for Creative Kiwi’s monthly management fee.</li>
<li>The Client acknowledges that while Creative Kiwi has expertise in online marketing and search engine optimisation, the degree of success of online marketing and search engine optimisation is both subjective and dependent on factors that are outside of Creative Kiwi’s control. Accordingly, Creative Kiwi is unable to guarantee the success of any online marketing or search engine optimisation undertaken on behalf of and/or for the Client.</li>
<li>Creative Kiwi will make reasonable endeavours to spend the entire media amount quoted and/or invoiced to the Client for the execution of marketing campaigns, however, the Client acknowledges that there are factors outside of Creative Kiwi’s control that may impact on the accrued media costs for the campaigns.<br><br>These factors outside of Creative Kiwi’s control include but are not limited to refunds from the marketing platform for invalid clicks and/or impressions, variable cost per click and/or cost per 1000 impressions, rounding off differences of less than $0.01 and differences in exchange rates across the campaign and invoicing timeframes.<br><br>The Client acknowledges and agrees that where there is a discrepancy between the media amount accrued and the media amount invoiced, Creative Kiwi will not be liable to refund any discrepancy to the Client where the cost of administering the refund outweighs the quantum or where the discrepancy only becomes evident more than 7 days of the invoiced period.</li>
<li>Creative Kiwi may choose to provide the Client with a performance guarantee for specific marketing campaigns. This guarantee is governed by the following terms:<br><ol><li>The performance target needs to be agreed upon by both Creative Kiwi and the Client prior to the campaign launching.</li>
<li>The campaign needs to be directly comparable to a pre-existing campaign against which the performance is being measured. Changes in campaign direction or objectives will not be covered by the guarantee. In the case that seasonality in the Client’s business or industry is likely to affect the demand for goods or services the performance will need to be measured based on comparable previous seasons.</li>
<li>This guarantee will only apply to paid media marketing campaigns run on either of the following advertising platforms: Facebook Ads, Google Ads, Google Display and Video 360.</li>
<li>This guarantee is based on the campaign’s performance at the end of 90 days from the day the campaign is launched. This guarantee will not be enforceable if the Client chooses to pause or terminate the campaign before the 90 day period is complete.</li>
<li>In the event that Creative Kiwi fails to meet the agreed target, Creative Kiwi agrees to refund the client for the service fees charged by Creative Kiwi for the specific campaign over the 90 day period. Creative Kiwi will not be liable for any fees paid to 3rd parties, including but not limited to Google and Facebook. Creative Kiwi will also not be liable for refunding fees for additional services rendered that are unrelated to the campaign being guaranteed.&nbsp;</li>
</ol></li>
</ol><h4><strong><br>11. PROOFING</strong></h4><p>Proofs of all work may be submitted for Clients approval and Creative Kiwi shall incur no liability for any errors not corrected by the Client in proofs submitted. Additional charges shall be made for any additional proofs that are required as a result of alterations required by the Client.</p><h4><strong><br>12. GUARANTEE</strong></h4><ol><li>In consideration of Creative Kiwi entering into a Contract to supply Products and/or Services to the Client, the Guarantor:
<ol><li>Guarantees payment of all monies owed by the Client to Creative Kiwi, and</li>
<li>Guarantees the performance by the Client of all obligations, responsibilities and covenants under the Contract.</li>
</ol></li>
<li>The Guarantor agrees that in the event of default by the Client in any payment, obligation, responsibility or covenant under the estimate or quotation, these Terms and Conditions or a Contract, the Guarantor may for all purposes be treated as the Client by Creative Kiwi who shall be under no obligation to take proceedings against the Client before taking proceedings against the Guarantor, and the Guarantor will execute a mortgage over his/her or its property to secure payment of all monies owed and outstanding by the Client to Creative Kiwi if requested by Creative Kiwi.</li>
<li>Should there be more than one Guarantor then their liability as Guarantors under this Guarantee shall be joint and several</li>
</ol><h4><strong><br>13. MISCELLANEOUS</strong></h4><ol><li>If any Condition or part of any Condition is held to be invalid or unenforceable the invalidity or unenforceability shall be deemed eliminated or modified to the minimum possible extent necessary to make the remainder of the Conditions enforceable.</li>
<li>Failure by Creative Kiwi to insist upon strict performance by the Client of any of the Conditions shall not be a waiver of any rights of Creative Kiwi on any subsequent occasion.</li>
<li>These Terms and Conditions and the Contract may only be varied by Creative Kiwi in writing at its discretion.</li>
<li>The Client may not assign or transfer any of its rights or obligations under or in connection with the Contract to any other person whatsoever.</li>
<li>Creative Kiwi reserves the right to sub-contract the performance of the Contract or any part of the Contract to any other party or person.</li>
<li>Neither party shall be liable for any delay, alteration or failure to perform any of its obligations under a Contract where occasioned by an event beyond that party’s reasonable control (“force majeure”) and such party shall be entitled to a reasonable extension of time for the performance of any such obligations.</li>
<li>The Client shall pay the costs and expenses including indemnity legal costs incurred by Creative Kiwi in exercising any of its rights or remedies or enforcing any of the Conditions. All Contracts made between Creative Kiwi and the Client shall be governed by and construed in accordance with the laws of New Zealand and the Client agrees to submit to the nonexclusive jurisdiction of the New Zealand Courts.</li>
<li>Any notice given by one party to the other shall be deemed to have been delivered 48 hours after posting to the recipients registered office or last known address and immediately if forwarded by facsimile or email. Packaging and supplying files will incur a cost and will be payable by the Client in advance of files being supplied.</li>
</ol><h4><strong><br>14. COLLECTION AND DISCLOSURE OF INFORMATION</strong></h4><p>Creative Kiwi may at any time collect, hold and use information relating to a Client for any purpose connected with its business including (but not limited to) direct marketing, debt recovery, credit reporting or assessment, and to register any security interest, including collecting information from, and disclosing information to, Related Companies, external credit reporting agencies, debt collection agencies, trade referees and other third parties. Information disclosed by Creative Kiwi to credit reporting agencies will be disclosed on the basis that it will be held and used by such agencies to provide credit reporting services. Under the Privacy Act 1993 (and any amendments thereto), individuals have rights to access to, and request correction of, their personal information by contacting Creative Kiwi.</p><p>The Client, any director signing on behalf of the Client and any Guarantor authorises Creative Kiwi to collect, hold and use information from any person or entity for any of the above purposes, and for such person or entity to disclose information to Creative Kiwi, and the Client further authorises Creative Kiwi to disclose information to any person or entity for any of the above purposes and such person or entity to collect, hold and use information from Creative Kiwi.</p><h4><strong><br>15. LAW</strong></h4><p>These Terms and Conditions shall be governed by the laws of New Zealand and shall be construed in all respects as a New Zealand contract.</p>
    </div>
</div>
